#!/bin/bash
set -eu
PGBIN=/usr/lib/postgresql/15/bin

echo "Running openshift build: ${OPENSHIFT_BUILD_NAME:-}"

# PGDATA_ROOT must be provided by Dockerfile
# PGDATA_GENERATION is expected to be supplied via openshift Deployment runtime
# environment, it should be an integer
if [[ -n ${PGDATA_GENERATION:-} ]]; then
    PGDATA=$PGDATA_ROOT/generation-$PGDATA_GENERATION
    echo "Using PGDATA=$PGDATA"
else
    # Last resort, use alphabetically last directory under PGDATA_ROOT, or, if
    # no subdirectory exist at all, PGDATA_ROOT itself
    PGDATA=$(find "$PGDATA_ROOT" -maxdepth 1 -type d | sort | tail -n1)
    echo "[WARNING] PGDATA_GENERATION is not set, falling back to PGDATA=$PGDATA"
fi

[[ -d "$PGDATA" ]] || echo "WARNING: not a directory: PGDATA=$PGDATA"

export PGDATA
exec $PGBIN/postgres --config-file=/etc/postgresql/15/main/postgresql.conf
