#!/bin/bash
set -e

if [[ "$#" -eq 0 ]]; then
    NAMES=(www webapp database)
elif [[ "$#" -eq 1 ]]; then
    NAMES=("$1")
else
    echo >&2 "bad cmd line options"
fi

for i in "${NAMES[@]}"; do
    docker build --tag glamr."$i" "$i"/
done
