version: "3"
services:
  www:
    image: glamr.www
    depends_on:
      - glamr-webapp
    restart: always
    ports:
      # port 8080 on host on all interfaces
      - 8080:8080
    volumes:
      - static:/glamr-webapp/static:ro
      - /usr/local/etc/glamr-staging-www-secrets:/secrets:ro
  glamr-webapp:
    image: glamr.webapp
    depends_on:
      - database
    restart: always
    volumes:
      # manage collectstatic writes here
      - static:/glamr-webapp/static:rw
      - krona:/glamr-webapp/krona-cache:rw
    environment:
      - DJANGO_DEBUG
      - DJANGO_ENABLE_TEST_VIEWS
      - DJANGO_PUBLIC_DATA_ROOT
      - DJANGO_GLOBUS_DIRECT_URL_BASE
      - DJANGO_GLOBUS_FILE_APP_URL_BASE
    healthcheck:
      test: ["CMD", "/glamr-webapp/healthcheck"]
      interval: 4s
      timeout: 5s
      retries: 2
  database:
    image: glamr.database
    restart: always
    shm_size: 1gb
    ports:
      # open port 54321 on all host interfaces
      - 54321:5432
    volumes:
      # permanent storage on host
      - /scratch/glamr-db-staging:/var/local/postgresql

volumes:
  static:
  krona:
