version: "3"
services:
  www:
    image: glamr.www
    depends_on:
      - glamr-webapp
    restart: always
    ports:
      # port 8080 on host on tunnel to reverse proxy
      - 10.0.0.2:8080:8080/tcp
    volumes:
      - static:/glamr-webapp/static:ro
      - /usr/local/etc/glamr-staging-www-secrets:/secrets:ro
      - /geomicro/data7/GLAMR-base/storage-local:/storage-local:ro
  glamr-webapp:
    image: glamr.webapp
    depends_on:
      - database
    restart: always
    volumes:
      # manage collectstatic writes here
      - static:/glamr-webapp/static:rw
      - krona:/glamr-webapp/krona-cache:rw
    environment:
      - DJANGO_DEBUG
      - DJANGO_ENABLE_TEST_VIEWS
      - DJANGO_PUBLIC_DATA_ROOT
      - DJANGO_GLOBUS_DIRECT_URL_BASE
      - DJANGO_GLOBUS_FILE_APP_URL_BASE
      - BASIC_AUTH_CREDENTIALS
    healthcheck:
      test: ["CMD", "/glamr-webapp/healthtest"]
      interval: 60s
      timeout: 10s
      retries: 2
  database:
    image: glamr.database
    restart: always
    shm_size: 4gb
    ports:
      # open port 54321 on host (all interfaces)
      - 54321:5432
    volumes:
      # permanent storage on host
      - /scratch/glamr-db-staging:/var/local/postgresql

volumes:
  static:
  krona:
