#!/bin/bash
#
# Download and process greatlakesomics.org apache server logs and generate
# web-analytic reports.
#
# This script is intended to be run as cron job on alpena, e.g.:
#
# 30 7 * * * openshift-gdick-web-app /usr/local/bin/get-glamr-apache-logs
#
# It can also be run standalone by the openshift-gdick-web-app or the root user.
#
set -eu
trap 'echo [ERROR] in $0 at line $LINENO exit code $?' ERR
source /etc/glamr-web-analytics.conf

DESTDIR=$VAR_DIR/daily-logs
LOG=$VAR_DIR/update.log

# Run as the openshift web app user so that we have permission to read log
# files and so that the created files have correct perms.
[[ "$(id -un)" == "$OPENSHIFT_USER" ]] || exec sudo -u "$OPENSHIFT_USER" -- "$0" "$@"


# Process options
download=true
while [[ $# -gt 0 ]]; do
    case $1 in
        --no-download) download=false;;
        *) echo >&2 "bad option: $1, allowed are --no-download"; exit 1;;
    esac
    shift
done

if ! [[ -t 0 && -t 1 ]]; then
    # non-interactive, e.g. run as cron job
    # keep a log file
    exec 1>"$LOG" 2>&1
fi

mkdir -p -- "$VAR_DIR"
cd "$VAR_DIR"

if $download; then
    mkdir -p -- "$DESTDIR"
    python3 -m glamr_ops.log retrieve --remove-original
    # TODO: get other logs
fi

# import apache hits
HITS_DATA_DIR=$VAR_DIR/hits.data
mkdir -p -- "$HITS_DATA_DIR"
python3 -m glamr_ops.log.apache import-hits --hits-data "$HITS_DATA_DIR"
python3 -m glamr_ops.log.apache plot --hits-data "$HITS_DATA_DIR" --outdir "$HTML_DIR" --format svg


function make-html () {
    title=$1
    shift
    filename=$(echo "$title" | tr ' [:upper:]' '-[:lower:]').html
    cmd=(goaccess - -a --log-format=COMBINED --html-report-title "$title" -o "$HTML_DIR/$filename" --browsers-file=/etc/goaccess/browsers.list --no-parsing-spinner)
    bot_opt='--ignore-crawlers'
    opts=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --no-ignore-crawlers) bot_opt=;;
            *) opts+=("$1")
        esac
        shift
    done

    [[ -n "$bot_opt" ]] && cmd+=("$bot_opt")
    cmd+=("${opts[@]}")
    echo >&2 "${cmd[*]}"
    "${cmd[@]}"
}

exit

alias mark-bots=cat

# Create HTML reports
find "$DESTDIR" -name "access.*.log" | tail -n8 | head -n7 | xargs cat | mark-bots | make-html "Last 7 days"
cat "$DESTDIR"/access.*.log | mark-bots | make-html "All-time report"
cat "$DESTDIR"/access.*.log | make-html "All-time with bots and everything" --no-ignore-crawlers
cat "$DESTDIR"/access.*.log | make-html "All-time bots only" --no-ignore-crawlers --crawlers-only

# Create query stats
update-glamr-search-queries -o "$HTML_DIR/queries.html" "$DESTDIR"/access.*.log
# Create outtage plots
update-glamr-outage --plot -o "$HTML_DIR" --uwsgi-log-base "$DESTDIR"/requests.log "$DESTDIR"/access.*.log
