#!/bin/bash
set -eu

PERSISTENT_LOGDIR=/webapp-logs/log

log () { echo "[$(date)] $*"; }

# if log volume is mounted use it for logging
if [[ -d $PERSISTENT_LOGDIR && -w $PERSISTENT_LOGDIR ]]; then
    # ./log in docker image assumed to be initially empty
    if rmdir ./log && ln -s $PERSISTENT_LOGDIR ./log; then
        log "logging to persistent storage"
    else
        log "ERROR check log directory"
    fi
else
    log "logs will be ephemeral"
fi

log "starting up glamr ..."
memcached -d -m 64 -p 11211 -l 127.0.0.1
if [[ ! -e secret.key ]]; then
    log "No secret.key file found -- deleting old sessions..."
    manage-mibios shell -c "from django.contrib.sessions.models import *; ret = Session.objects.all().delete(); print('Sessions deleted:', ret)" &
fi
manage-mibios collectstatic --no-input --clear -v 2 &
manage-mibios generate_model_graphs &
exec uwsgi --chdir "$APP_BASE_DIR" --ini /etc/uwsgi.ini
