#!/bin/bash
set -eEu

# shellcheck disable=SC1091
source common.sh

trap '' EXIT  # do not use clean from common.sh

# User with access and ownership of production storage postgres data dir
OPENSHIFT_USER=openshift-gdick-web-app
# Paths at production storage (exported as they must be available under sudo)
export TARGET_BASE=/nfs/turbo/lsa-gdick-openshift/postgres/data
export DATADIR_TEMPLATE=$TARGET_BASE/generation-
export PGHOME

[[ "${1:-}" =~ [0-9]+ ]] || err "usage: $0 <N>   (N must be the generation number)"
next_generation=$1
export target=$TARGET_BASE/generation-$next_generation

[[ -z "$(ls -a1 ./run/.*PGSQL* 2>/dev/null)" ]] || err "socket file exists, postgres may still be running?"

# make source readable, permission bits should be fine
sudo chown -R "${OPENSHIFT_USER}:root" -- "$PGHOME"

function check () {
    set -eu
    # Test if target storage looks as expected
    [[ -d "$TARGET_BASE" ]] || err "no data directory: $TARGET_BASE"
    [[ -d "$PGHOME" && -r "$PGHOME" ]] || err "source directory unreadable: $PGHOME"
    [[ ! -e "$target" ]] || err "Destination already exists: $target"

    df -h --output=source,used,avail,pcent "$(dirname "$TARGET_BASE")"
    echo "                                                                         ^"
    echo "source disk usage: $(du -hs "$PGHOME")              |"
}
sudo -u "$OPENSHIFT_USER" -E -- bash -c "$(declare -f check err); check"

echo "DO WE HAVE SUFFICIENT STORAGE SPACE? Press <enter> or ^C  ---------------+"
read -r || { echo "abort by user"; exit; }

function prepare () {
    set -eu
    # setup new data directory
    >&2 mkdir -v --mode 0700 -- "$target"
}
sudo -u "$OPENSHIFT_USER" -E -- bash -c "$(declare -f prepare err); prepare"
echo "DB target: $target"

# rsync source must have slash
rsync_cmd=(sudo -u "$OPENSHIFT_USER" -- rsync -a --info=progress2 "$PGHOME/data/" "$target")
echo "rsync command:"
echo "${rsync_cmd[*]}"
echo "Confirm running rsync by <enter> or abort by ^C "
read -r || { echo "abort by user"; exit; }
"${rsync_cmd[@]}"
